global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'api-service'
    static_configs:
      - targets: ['api-server:8080']
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: 'redirect-service' 
    static_configs:
      - targets: ['redirect-server:8081']
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']